name: Actualización Diaria del Horóscopo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install
        working-directory: horoscopo

      - name: Ejecutar Script y Generar index.html
        run: node update.js
        working-directory: horoscopo
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Configurar Git para el commit automático
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        working-directory: horoscopo

      - name: Commit y Push de los cambios si existen
        run: |
          if git diff --exit-code index.html; then
            echo "No se encontraron cambios en index.html. Saltando commit."
          else
            git add index.html
            git commit -m "Actualización automática del Horóscopo por Gemini API"
            git push
          fi
        working-directory: horoscopo
